stages:
  - dev-build
  - dev-deploy
  - release
  - prod

dev-build-job:
  stage: dev-build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID -f ./docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  after_script:
    - docker logout $CI_REGISTRY



dev-deploy-job:
  stage: dev-deploy
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - cd docker
    - docker compose pull
    - docker compose down
    - docker compose up -d
  after_script:
    - docker logout $CI_REGISTRY
