stages:
  - dev
  - release
  - prod


dev-build-job:
  stage: dev
  image: docker:24
  before_script:
    - 'echo $CI_REGISTRY_USER'
    - 'echo $CI_REGISTRY_PASSWORD'
    - 'echo $CI_REGISTRY'
    - 'echo $CI_PIPELINE_ID'
    - 'echo $CI_REGISTRY_IMAGE'
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - 'echo build'

dev-deploy-job:
  stage: dev
  script:
    - 'echo deploy'