stages:
  - dev-build
  - dev-deploy
  - release
  - prod

dev-build-job:
  stage: dev-build
  image: docker:24
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" -f ./docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
  only:
    - develop
  after_script:
    - docker logout $CI_REGISTRY




dev-deploy-job:
  stage: dev-deploy
  script:
    - echo "deploy"