stages:
  - dev


dev-build-job:
  stage: dev
  before_script:
    - 'echo "CI_REGISTRY_USER: ${CI_REGISTRY_USER:-not set}"'
    - 'echo "CI_REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD:-not set}"'
    - 'echo "CI_REGISTRY: ${CI_REGISTRY:-not set}"'
  script:
    - 'echo build'

dev-deploy-job:
  stage: dev
  script:
    - 'echo deploy'