stages:
  - dev


dev-build-job:
  stage: dev
  before_script:
    - 'echo $CI_REGISTRY_USER'
    - 'echo $CI_REGISTRY_PASSWORD'
    - 'echo $CI_REGISTRY_'
  script:
    - 'echo build'

dev-deploy-job:
  stage: dev
  script:
    - 'echo deploy'