version: "3"
services:
  shop-backend:
    image: registry.gitlab.com/tech7684941/shop:${CI_PIPELINE_ID}
    networks:
      - web
      - db-back
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend1.rule=Host(`stage.elsa-gallery.shop`)"
      - "traefik.http.routers.backend1.entrypoints=web,websecure"  # Allow both HTTP and HTTPS
      - "traefik.http.routers.backend1.tls=true"  # Enable TLS
      - "traefik.http.services.backend1.loadbalancer.server.port=3010"
      - "traefik.http.middlewares.backend1-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.backend1-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.backend1.middlewares=backend1-https-redirect"
    # Remove the ports section as Traefik will handle the routing

networks:
  web:
    external: true
  db-back:
    external: true